import { NavItem, OrderStatusType } from '@/types';
import {
  IconBoxSeam,
  IconBrandYoutube,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconCurrentLocation,
  IconLayoutDashboard,
  IconNotebook,
  IconPackage,
  IconPackageExport,
  IconPackageOff,
  IconReceipt2,
  IconSettings,
  IconShoppingCart,
  IconTruckDelivery,
  IconTruckLoading,
  IconShoppingCartOff,
  IconUser,
  IconUserPlus,
  IconUserQuestion,
  IconUsers,
  IconCoin,
  IconCoinOff,
  IconClockDollar,
} from '@tabler/icons-react';

export enum packOptions {
  DAMREJ = 'DAMREJ',
  AJEJA = 'AJEJA',
  MACHROU3 = 'MACHROU3',
}
export enum roleOptions {
  ADMIN = 'ADMIN',
  SELLER = 'SELLER',
  SUPPLIER = 'SUPPLIER',
}

export const adminNavItems: NavItem[] = [
  {
    title: 'dashboard',
    href: '/dashboard/admin',
    icon: <IconLayoutDashboard />,
  },
  {
    title: 'marketplace',
    href: '/dashboard/marketplace',
    icon: <IconBuildingStore />,
  },
  {
    title: 'leads',
    href: '/dashboard/admin/leads',
    icon: <IconUserQuestion />,
  },
  {
    title: 'course',
    href: '/dashboard/admin/course',
    icon: <IconBrandYoutube />,
  },
  {
    title: 'sellers',
    href: '/dashboard/admin/sellers',
    icon: <IconUsers />,
  },
  {
    title: 'suppliers',
    href: '/dashboard/admin/suppliers',
    icon: <IconBuildingWarehouse />,
  },
  {
    title: 'products',
    href: '/dashboard/admin/products',
    icon: <IconBoxSeam />,
  },
  {
    title: 'orders',
    href: '/dashboard/admin/orders',
    icon: <IconShoppingCart />,
  },
  {
    title: 'pickups',
    href: '/dashboard/admin/pickups',
    icon: <IconTruckDelivery />,
  },
  {
    title: 'transactions',
    href: '/dashboard/admin/transactions',
    icon: <IconReceipt2 />,
  },
  {
    title: 'settings',
    href: '/dashboard/admin/settings',
    icon: <IconSettings />,
  },
];

export const sellerNavItems: NavItem[] = [
  {
    title: 'dashboard',
    href: '/dashboard/seller',
    icon: <IconLayoutDashboard />,
  },
  {
    title: 'marketplace',
    href: '/dashboard/marketplace',
    icon: <IconBuildingStore />,
  },
  {
    title: 'course',
    href: '/dashboard/seller/course',
    icon: <IconBrandYoutube />,
  },
  {
    title: 'my-products',
    href: '/dashboard/seller/my-products',
    icon: <IconBoxSeam />,
  },
  {
    title: 'orders',
    href: '/dashboard/seller/orders',
    icon: <IconShoppingCart />,
  },
  {
    title: 'transactions',
    href: '/dashboard/seller/transactions',
    icon: <IconReceipt2 />,
  },
  {
    title: 'settings',
    href: '/dashboard/seller/settings',
    icon: <IconSettings />,
  },
];

export const supplierNavItems: NavItem[] = [
  {
    title: 'dashboard',
    href: '/dashboard/supplier',
    icon: <IconLayoutDashboard />,
  },
  {
    title: 'marketplace',
    href: '/dashboard/marketplace',
    icon: <IconBuildingStore />,
  },
  {
    title: 'products',
    href: '/dashboard/supplier/products',
    icon: <IconBoxSeam />,
  },
  {
    title: 'orders',
    href: '/dashboard/supplier/orders',
    icon: <IconShoppingCart />,
  },
  {
    title: 'pickups',
    href: '/dashboard/supplier/pickups',
    icon: <IconTruckDelivery />,
  },
  {
    title: 'transactions',
    href: '/dashboard/supplier/transactions',
    icon: <IconReceipt2 />,
  },
  {
    title: 'settings',
    href: '/dashboard/supplier/settings',
    icon: <IconSettings />,
  },
];

export const MEDIA_HOSTNAME = 'https://utfs.io/f/';

export const notificationIcons = {
  ADMIN_NEW_PRODUCT: IconPackage,
  ADMIN_NEW_SELLER: IconUserPlus,
  ADMIN_NEW_LEAD: IconUserQuestion,
  SUPPLIER_PRODUCT_PUBLISHED: IconPackageExport,
  SUPPLIER_PRODUCT_UNPUBLISHED: IconPackageOff,
  SUPPLIER_NEW_ORDER: IconShoppingCart,
  ADMIN_NEW_ORDER: IconShoppingCart,
  SELLER_STOCK_CHANGED: IconTruckLoading,
  ORDER_STATUS_CHANGED: IconCurrentLocation,
  ORDER_CANCELLED: IconShoppingCartOff,
  NEW_PICKUP: IconTruckDelivery,
  NEW_TRANSACTION: IconReceipt2,
  NEW_WITHDRAW_REQUEST: IconClockDollar,
  WITHDRAW_REQUEST_APPROVED: IconCoin,
  WITHDRAW_REQUEST_DENIED: IconCoinOff,
};

export const notificationMessages = {
  ADMIN_NEW_PRODUCT: 'admin-new-product',
  ADMIN_NEW_SELLER: 'admin-new-seller',
  ADMIN_NEW_LEAD: 'admin-new-lead',
  SUPPLIER_PRODUCT_PUBLISHED: 'supplier-product-published',
  SUPPLIER_PRODUCT_UNPUBLISHED: 'supplier-product-unpublished',
  SUPPLIER_NEW_ORDER: 'supplier-new-order',
  ADMIN_NEW_ORDER: 'admin-new-order',
  SELLER_STOCK_CHANGED: 'seller-stock-changed',
  ORDER_STATUS_CHANGED: 'order-status-changed',
  ORDER_CANCELLED: 'order-cancelled',
  NEW_PICKUP: 'new-pickup',
  NEW_TRANSACTION: 'new-transaction',
  NEW_WITHDRAW_REQUEST: 'new-withdraw-request',
  WITHDRAW_REQUEST_APPROVED: 'withdraw-request-approved',
  WITHDRAW_REQUEST_DENIED: 'withdraw-request-declined',
};

export const localeOptions = {
  EN: 'en',
  FR: 'fr',
};

export const DEFAULT_PASSWORD = 'ECOMNESS2024';

export enum productCategoryOptions {
  FURNITURE = 'FURNITURE',
  ACCESSORIES = 'ACCESSORIES',
  KITCHEN = 'KITCHEN',
  DECORATION = 'DECORATION',
  CAR_ACCESSORIES = 'CAR_ACCESSORIES',
  HOME_APPLIANCES = 'HOME_APPLIANCES',
  ELECTRONICS = 'ELECTRONICS',
  CLOTHING = 'CLOTHING',
  BEAUTY = 'BEAUTY',
  SPORTS = 'SPORTS',
  TOYS = 'TOYS',
  JEWELRY = 'JEWELRY',
  GARDEN = 'GARDEN',
}

export const productCategoryData = [
  {
    name: productCategoryOptions.FURNITURE,
    imageUrl: '/img/furniture.png',
  },
  {
    name: productCategoryOptions.ACCESSORIES,
    imageUrl: '/img/accessories.png',
  },
  {
    name: productCategoryOptions.KITCHEN,
    imageUrl: '/img/kitchen.png',
  },
  {
    name: productCategoryOptions.DECORATION,
    imageUrl: '/img/decoration.png',
  },
  {
    name: productCategoryOptions.TOYS,
    imageUrl: '/img/baby-kids.webp',
  },
  {
    name: productCategoryOptions.HOME_APPLIANCES,
    imageUrl: '/img/appliances.webp',
  },

  {
    name: productCategoryOptions.ELECTRONICS,
    imageUrl: '/img/technology.webp',
  },
  {
    name: productCategoryOptions.CLOTHING,
    imageUrl: '/img/fashion.png',
  },
  {
    name: productCategoryOptions.BEAUTY,
    imageUrl: '/img/beauty.webp',
  },
  {
    name: productCategoryOptions.GARDEN,
    imageUrl: '/img/garden.png',
  },
  {
    name: productCategoryOptions.SPORTS,
    imageUrl: '/img/sport.webp',
  },
  {
    name: productCategoryOptions.CAR_ACCESSORIES,
    imageUrl: '/img/auto-parts.webp',
  },
  {
    name: productCategoryOptions.JEWELRY,
    imageUrl: '/img/jewelry.png',
  },
];

export enum sizeOptions {
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
  XXL = 'XXL',
  XXXL = 'XXXL',
}

export enum colorOptions {
  RED = 'RED',
  BLUE = 'BLUE',
  GREEN = 'GREEN',
  YELLOW = 'YELLOW',
  BLACK = 'BLACK',
  WHITE = 'WHITE',
  ORANGE = 'ORANGE',
  PURPLE = 'PURPLE',
  PINK = 'PINK',
  LIGHT_BLUE = 'LIGHT_BLUE',
  NAVY_BLUE = 'NAVY_BLUE',
  TURQUOISE = 'TURQUOISE',
  BEIGE = 'BEIGE',
  BROWN = 'BROWN',
  GRAY = 'GRAY',
}

export const colorHexMap: { [key in colorOptions]: string } = {
  [colorOptions.RED]: '#FF0000',
  [colorOptions.BLUE]: '#0000FF',
  [colorOptions.GREEN]: '#00FF00',
  [colorOptions.YELLOW]: '#FFFF00',
  [colorOptions.BLACK]: '#000000',
  [colorOptions.WHITE]: '#FFFFFF',
  [colorOptions.ORANGE]: '#FFA500',
  [colorOptions.PURPLE]: '#800080',
  [colorOptions.PINK]: '#FFC0CB',
  [colorOptions.LIGHT_BLUE]: '#ADD8E6',
  [colorOptions.NAVY_BLUE]: '#000080',
  [colorOptions.TURQUOISE]: '#40E0D0',
  [colorOptions.BEIGE]: '#F5F5DC',
  [colorOptions.BROWN]: '#A52A2A',
  [colorOptions.GRAY]: '#808080',
};

export const orderStatuses = [
  // Custom statuses
  {
    UpdateCode: 'EC00',
    ProblemCode: null,
    Key: 'awaiting-packaging-EC00',
    Color: 'bg-blue-300 text-white',
    Description: 'awaiting-packaging-description-EC00',
  },
  {
    UpdateCode: 'EC01',
    ProblemCode: null,
    Key: 'seller-cancelled-EC01',
    Color: 'bg-destructive text-white',
    Description: 'seller-cancelled-description-EC01',
  },
  {
    UpdateCode: 'EC02',
    ProblemCode: null,
    Key: 'finished-EC02',
    Color: 'bg-destructive text-white',
    Description: 'paid-description-EC01',
  },
  {
    UpdateCode: 'SH278',
    ProblemCode: null,
    Key: 'on-going-SH278',
    Color: 'bg-blue-300 text-white',
    Description: 'on-going-description-SH278',
  },
  // Statuses based on provided data
  {
    UpdateCode: 'SH001',
    ProblemCode: null,
    Key: 'received-at-facility-SH001',
    Color: 'bg-blue-300 text-white',
    Description: 'received-at-facility-description-SH001',
  },
  {
    UpdateCode: 'SH002',
    ProblemCode: null,
    Key: 'received-at-facility-SH002',
    Color: 'bg-blue-300 text-white',
    Description: 'received-at-facility-description-SH002',
  },
  {
    UpdateCode: 'SH003',
    ProblemCode: null,
    Key: 'out-for-delivery-SH003',
    Color: 'bg-blue-300 text-white',
    Description: 'out-for-delivery-description-SH003',
  },
  {
    UpdateCode: 'SH004',
    ProblemCode: null,
    Key: 'partial-out-for-delivery-SH004',
    Color: 'bg-blue-300 text-white',
    Description: 'partial-out-for-delivery-description-SH004',
  },
  {
    UpdateCode: 'SH005',
    ProblemCode: null,
    Key: 'delivered-SH005',
    Color: 'bg-success text-white',
    Description: 'delivered-description-SH005',
  },
  {
    UpdateCode: 'SH006',
    ProblemCode: null,
    Key: 'collected-SH006',
    Color: 'bg-success text-white',
    Description: 'collected-description-SH006',
  },
  {
    UpdateCode: 'SH007',
    ProblemCode: null,
    Key: 'postal-delivery-SH007',
    Color: 'bg-blue-300 text-white',
    Description: 'postal-delivery-description-SH007',
  },
  {
    UpdateCode: 'SH008',
    ProblemCode: null,
    Key: 'shipment-on-hold-SH008',
    Color: 'bg-destructive text-white',
    Description: 'shipment-on-hold-description-SH008',
  },
  {
    UpdateCode: 'SH011',
    ProblemCode: null,
    Key: 'picked-up-SH011',
    Color: 'bg-success text-white',
    Description: 'picked-up-description-SH011',
  },
  {
    UpdateCode: 'SH012',
    ProblemCode: null,
    Key: 'picked-up-from-shipper-SH012',
    Color: 'bg-success text-white',
    Description: 'picked-up-from-shipper-description-SH012',
  },
  {
    UpdateCode: 'SH014',
    ProblemCode: null,
    Key: 'record-created-SH014',
    Color: 'bg-gray-400 text-white',
    Description: 'record-created-description-SH014',
  },
  {
    UpdateCode: 'SH017',
    ProblemCode: null,
    Key: 'n-a-SH017',
    Color: 'bg-gray-400 text-white',
    Description: 'n-a-description-SH017',
  },
  {
    UpdateCode: 'SH024',
    ProblemCode: null,
    Key: 'n-a-SH024',
    Color: 'bg-gray-400 text-white',
    Description: 'n-a-description-SH024',
  },
  {
    UpdateCode: 'SH030',
    ProblemCode: null,
    Key: 'still-on-hold-SH030',
    Color: 'bg-destructive text-white',
    Description: 'still-on-hold-description-SH030',
  },

  // Attempted delivery with detailed problem codes
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A00',
    Key: 'attempted-delivery-SH033-A00',
    Color: 'bg-destructive text-white',
    Description: 'attempted-delivery-description-SH033-A00',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A01',
    Key: 'no-one-home-SH033-A01',
    Color: 'bg-destructive text-white',
    Description: 'no-one-home-description-SH033-A01',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A02',
    Key: 'office-closed-SH033-A02',
    Color: 'bg-destructive text-white',
    Description: 'office-closed-description-SH033-A02',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A03',
    Key: 'customer-not-available-SH033-A03',
    Color: 'bg-destructive text-white',
    Description: 'customer-not-available-description-SH033-A03',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A04',
    Key: 'address-changed-SH033-A04',
    Color: 'bg-destructive text-white',
    Description: 'address-changed-description-SH033-A04',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A05',
    Key: 'incorrect-address-SH033-A05',
    Color: 'bg-destructive text-white',
    Description: 'incorrect-address-description-SH033-A05',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A06',
    Key: 'restricted-access-SH033-A06',
    Color: 'bg-destructive text-white',
    Description: 'restricted-access-description-SH033-A06',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A07',
    Key: 'time-restriction-SH033-A07',
    Color: 'bg-destructive text-white',
    Description: 'time-restriction-description-SH033-A07',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A08',
    Key: 'payment-not-ready-SH033-A08',
    Color: 'bg-destructive text-white',
    Description: 'payment-not-ready-description-SH033-A08',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A10',
    Key: 'next-business-day-SH033-A10',
    Color: 'bg-destructive text-white',
    Description: 'next-business-day-description-SH033-A10',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A11',
    Key: 'rescheduled-next-day-SH033-A11',
    Color: 'bg-destructive text-white',
    Description: 'rescheduled-next-day-description-SH033-A11',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A12',
    Key: 'rescheduled-next-day-SH033-A12',
    Color: 'bg-destructive text-white',
    Description: 'rescheduled-next-day-description-SH033-A12',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A13',
    Key: 'no-contact-SH033-A13',
    Color: 'bg-destructive text-white',
    Description: 'no-contact-description-SH033-A13',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A14',
    Key: 'business-closed-SH033-A14',
    Color: 'bg-destructive text-white',
    Description: 'business-closed-description-SH033-A14',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A15',
    Key: 'moved-address-needed-SH033-A15',
    Color: 'bg-destructive text-white',
    Description: 'moved-address-needed-description-SH033-A15',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A16',
    Key: 'awaiting-correct-address-SH033-A16',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-correct-address-description-SH033-A16',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A17',
    Key: 'pending-instructions-SH033-A17',
    Color: 'bg-destructive text-white',
    Description: 'pending-instructions-description-SH033-A17',
  },
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A20',
    Key: 'unable-to-deliver-contact-office-SH033-A20',
    Color: 'bg-destructive text-white',
    Description: 'unable-to-deliver-contact-office-description-SH033-A20',
  },

  // Customs and clearance-related statuses
  {
    UpdateCode: 'SH035',
    ProblemCode: null,
    Key: 'awaiting-clearance-SH035',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-clearance-description-SH035',
  },
  {
    UpdateCode: 'SH041',
    ProblemCode: null,
    Key: 'cleared-customs-SH041',
    Color: 'bg-success text-white',
    Description: 'cleared-customs-description-SH041',
  },

  // Delay and reschedule statuses
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U00',
    Key: 'delay-rescheduled-U00-SH043',
    Color: 'bg-destructive text-white',
    Description: 'delay-rescheduled-U00-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U01',
    Key: 'delay-next-day-U01-SH043',
    Color: 'bg-destructive text-white',
    Description: 'delay-next-day-U01-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U02',
    Key: 'address-incomplete-U02-SH043',
    Color: 'bg-destructive text-white',
    Description: 'address-incomplete-U02-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U03',
    Key: 'delayed-next-day-U03-SH043',
    Color: 'bg-destructive text-white',
    Description: 'delayed-next-day-U03-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U04',
    Key: 'delayed-next-day-again-U04-SH043',
    Color: 'bg-destructive text-white',
    Description: 'delayed-next-day-again-U04-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U07',
    Key: 'awaiting-address-U07-SH043',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-address-U07-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U09',
    Key: 'office-closed-U09-SH043',
    Color: 'bg-destructive text-white',
    Description: 'office-closed-U09-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U10',
    Key: 'payment-declined-U10-SH043',
    Color: 'bg-destructive text-white',
    Description: 'payment-declined-U10-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U18',
    Key: 'missing-id-proof-U18-SH043',
    Color: 'bg-destructive text-white',
    Description: 'missing-id-proof-U18-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U19',
    Key: 'id-proof-unclear-U19-SH043',
    Color: 'bg-destructive text-white',
    Description: 'id-proof-unclear-U19-description-SH043',
  },

  // Further delay statuses
  {
    UpdateCode: 'SH044',
    ProblemCode: 'M00',
    Key: 'further-delay-M00-SH044',
    Color: 'bg-destructive text-white',
    Description: 'further-delay-M00-description-SH044',
  },
  {
    UpdateCode: 'SH044',
    ProblemCode: 'M01',
    Key: 'delay-rescheduled-M01-SH044',
    Color: 'bg-destructive text-white',
    Description: 'delay-rescheduled-M01-description-SH044',
  },
  {
    UpdateCode: 'SH044',
    ProblemCode: 'M02',
    Key: 'delay-rescheduled-M02-SH044',
    Color: 'bg-destructive text-white',
    Description: 'delay-rescheduled-M02-description-SH044',
  },

  // Origin and return statuses
  {
    UpdateCode: 'SH047',
    ProblemCode: null,
    Key: 'origin-facility-SH047',
    Color: 'bg-blue-300 text-white',
    Description: 'origin-facility-description-SH047',
  },
  {
    UpdateCode: 'SH069',
    ProblemCode: null,
    Key: 'to-be-returned-SH069',
    Color: 'bg-destructive text-white',
    Description: 'to-be-returned-description-SH069',
  },
  {
    UpdateCode: 'SH070',
    ProblemCode: null,
    Key: 'redirected-address-SH070',
    Color: 'bg-destructive text-white',
    Description: 'redirected-address-description-SH070',
  },
  {
    UpdateCode: 'SH073',
    ProblemCode: null,
    Key: 'forwarded-remote-location-SH073',
    Color: 'bg-blue-300 text-white',
    Description: 'forwarded-remote-location-description-SH073',
  },

  // Situation updates
  {
    UpdateCode: 'SH076',
    ProblemCode: 'R01',
    Key: 'situation-update-R01-SH076',
    Color: 'bg-blue-300 text-white',
    Description: 'situation-update-R01-description-SH076',
  },
  {
    UpdateCode: 'SH076',
    ProblemCode: 'R02',
    Key: 'weather-delay-R02-SH076',
    Color: 'bg-destructive text-white',
    Description: 'weather-delay-R02-description-SH076',
  },
  {
    UpdateCode: 'SH076',
    ProblemCode: 'R03',
    Key: 'holiday-delay-R03-SH076',
    Color: 'bg-destructive text-white',
    Description: 'holiday-delay-R03-description-SH076',
  },
  {
    UpdateCode: 'SH076',
    ProblemCode: 'R04',
    Key: 'delay-rescheduled-R04-SH076',
    Color: 'bg-destructive text-white',
    Description: 'delay-rescheduled-R04-description-SH076',
  },

  {
    UpdateCode: 'SH077',
    ProblemCode: null,
    Key: 'forwarded-aramex-office-SH077',
    Color: 'bg-blue-300 text-white',
    Description: 'forwarded-aramex-office-description-SH077',
  },
  {
    UpdateCode: 'SH110',
    ProblemCode: null,
    Key: 'delivery-office-SH110',
    Color: 'bg-blue-300 text-white',
    Description: 'delivery-office-description-SH110',
  },

  // Partial delivery
  {
    UpdateCode: 'SH154',
    ProblemCode: null,
    Key: 'partial-delivery-SH154',
    Color: 'bg-destructive text-white',
    Description: 'partial-delivery-description-SH154',
  },

  // Customs and clearance delays
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C00',
    Key: 'customs-clearance-pending-C00-SH156',
    Color: 'bg-destructive text-white',
    Description: 'customs-clearance-pending-C00-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C01',
    Key: 'awaiting-customer-instructions-C01-SH156',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-customer-instructions-C01-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C02',
    Key: 'customs-clearance-C02-SH156',
    Color: 'bg-blue-300 text-white',
    Description: 'customs-clearance-C02-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C03',
    Key: 'customs-clearance-C03-SH156',
    Color: 'bg-blue-300 text-white',
    Description: 'customs-clearance-C03-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C04',
    Key: 'awaiting-duty-payment-C04-SH156',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-duty-payment-C04-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C05',
    Key: 'misdeclaration-C05-SH156',
    Color: 'bg-destructive text-white',
    Description: 'misdeclaration-C05-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C06',
    Key: 'unacceptable-commodities-C06-SH156',
    Color: 'bg-destructive text-white',
    Description: 'unacceptable-commodities-C06-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C07',
    Key: 'incomplete-info-C07-SH156',
    Color: 'bg-destructive text-white',
    Description: 'incomplete-info-C07-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C08',
    Key: 'urgent-instructions-C08-SH156',
    Color: 'bg-destructive text-white',
    Description: 'urgent-instructions-C08-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C09',
    Key: 'awaiting-invoice-C09-SH156',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-invoice-C09-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C10',
    Key: 'fda-certificate-C10-SH156',
    Color: 'bg-destructive text-white',
    Description: 'fda-certificate-C10-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C15',
    Key: 'us-customs-confiscation-C15-SH156',
    Color: 'bg-destructive text-white',
    Description: 'us-customs-confiscation-C15-description-SH156',
  },
  {
    UpdateCode: 'SH156',
    ProblemCode: 'C16',
    Key: 'us-customs-urgent-C16-SH156',
    Color: 'bg-destructive text-white',
    Description: 'us-customs-urgent-C16-description-SH156',
  },

  // Unable to forward due to local issues
  {
    UpdateCode: 'SH157',
    ProblemCode: 'G00',
    Key: 'unable-to-forward-G00-SH157',
    Color: 'bg-destructive text-white',
    Description: 'unable-to-forward-G00-description-SH157',
  },
  {
    UpdateCode: 'SH157',
    ProblemCode: 'G02',
    Key: 'unable-to-forward-contact-office-G02-SH157',
    Color: 'bg-destructive text-white',
    Description: 'unable-to-forward-contact-office-G02-description-SH157',
  },
  {
    UpdateCode: 'SH157',
    ProblemCode: 'G03',
    Key: 'unable-to-deliver-G03-SH157',
    Color: 'bg-destructive text-white',
    Description: 'unable-to-deliver-G03-description-SH157',
  },

  // Delay-specific statuses
  {
    UpdateCode: 'SH158',
    ProblemCode: 'C25',
    Key: 'customs-clearance-delay-C25-SH158',
    Color: 'bg-destructive text-white',
    Description: 'customs-clearance-delay-C25-description-SH158',
  },

  // Received at operations facility
  {
    UpdateCode: 'SH160',
    ProblemCode: 'V00',
    Key: 'received-facility-V00-SH160',
    Color: 'bg-blue-300 text-white',
    Description: 'received-facility-V00-description-SH160',
  },
  {
    UpdateCode: 'SH160',
    ProblemCode: 'V01',
    Key: 'received-facility-V01-SH160',
    Color: 'bg-blue-300 text-white',
    Description: 'received-facility-V01-description-SH160',
  },
  {
    UpdateCode: 'SH160',
    ProblemCode: 'D41',
    Key: 'awaiting-shipper-data-D41-SH160',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-shipper-data-D41-description-SH160',
  },

  // Held for consignee pickup
  {
    UpdateCode: 'SH164',
    ProblemCode: null,
    Key: 'held-consignee-pickup-SH164',
    Color: 'bg-destructive text-white',
    Description: 'held-consignee-pickup-description-SH164',
  },
  {
    UpdateCode: 'SH203',
    ProblemCode: null,
    Key: 'record-created-SH203',
    Color: 'bg-success text-white',
    Description: 'record-created-description-SH203',
  },

  // Operations scanned and consignee pickup
  {
    UpdateCode: 'SH495',
    ProblemCode: null,
    Key: 'operations-scanned-SH495',
    Color: 'bg-blue-300 text-white',
    Description: 'operations-scanned-description-SH495',
  },
  {
    UpdateCode: 'SH496',
    ProblemCode: null,
    Key: 'consignee-picked-up-SH496',
    Color: 'bg-success text-white',
    Description: 'consignee-picked-up-description-SH496',
  },
  {
    UpdateCode: 'SH498',
    ProblemCode: null,
    Key: 'contact-attempts-completed-SH498',
    Color: 'bg-destructive text-white',
    Description: 'contact-attempts-completed-description-SH498',
  },

  // Auto-payment and financial statuses
  {
    UpdateCode: 'SH505',
    ProblemCode: null,
    Key: 'payment-cancelled-SH505',
    Color: 'bg-destructive text-white',
    Description: 'payment-cancelled-description-SH505',
  },
  {
    UpdateCode: 'SH513',
    ProblemCode: null,
    Key: 'auto-scheduled-delivery-SH513',
    Color: 'bg-blue-300 text-white',
    Description: 'auto-scheduled-delivery-description-SH513',
  },
  {
    UpdateCode: 'SH515',
    ProblemCode: null,
    Key: 'courier-called-customer-SH515',
    Color: 'bg-blue-300 text-white',
    Description: 'courier-called-customer-description-SH515',
  },
  {
    UpdateCode: 'SH515',
    ProblemCode: 'L1',
    Key: 'courier-called-no-response-SH515-L1',
    Color: 'bg-blue-300 text-white',
    Description: 'courier-called-no-response-description-SH515-L1',
  },
  {
    UpdateCode: 'SH515',
    ProblemCode: 'L2',
    Key: 'courier-called-busy-SH515-L2',
    Color: 'bg-blue-300 text-white',
    Description: 'courier-called-busy-description-SH515-L2',
  },
  {
    UpdateCode: 'SH516',
    ProblemCode: null,
    Key: 'customer-called-responded-SH516',
    Color: 'bg-blue-300 text-white',
    Description: 'customer-called-responded-description-SH516',
  },
  {
    UpdateCode: 'SH521',
    ProblemCode: 'B3',
    Key: 'prepared-for-collection-B3-SH521',
    Color: 'bg-blue-300 text-white',
    Description: 'prepared-for-collection-B3-description-SH521',
  },
  {
    UpdateCode: 'SH521',
    ProblemCode: 'B4',
    Key: 'scheduled-for-delivery-B4-SH521',
    Color: 'bg-blue-300 text-white',
    Description: 'scheduled-for-delivery-B4-description-SH521',
  },

  // Local office contact
  {
    UpdateCode: 'SH033',
    ProblemCode: 'A21',
    Key: 'local-office-contact-A21-SH033',
    Color: 'bg-destructive text-white',
    Description: 'local-office-contact-A21-description-SH033',
  },

  // Additional statuses
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U03',
    Key: 'delayed-next-day-U03-SH043',
    Color: 'bg-destructive text-white',
    Description: 'delayed-next-day-U03-description-SH043',
  },
  {
    UpdateCode: 'SH043',
    ProblemCode: 'U04',
    Key: 'delayed-next-day-again-U04-SH043',
    Color: 'bg-destructive text-white',
    Description: 'delayed-next-day-again-U04-description-SH043',
  },
  {
    UpdateCode: 'SH076',
    ProblemCode: 'R02',
    Key: 'weather-delay-R02-SH076',
    Color: 'bg-destructive text-white',
    Description: 'weather-delay-R02-description-SH076',
  },
  {
    UpdateCode: 'SH076',
    ProblemCode: 'R03',
    Key: 'holiday-delay-R03-SH076',
    Color: 'bg-destructive text-white',
    Description: 'holiday-delay-R03-description-SH076',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D08',
    Key: 'additional-packing-D08-SH162',
    Color: 'bg-destructive text-white',
    Description: 'additional-packing-D08-description-SH162',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D10',
    Key: 'contact-local-office-D10-SH162',
    Color: 'bg-destructive text-white',
    Description: 'contact-local-office-D10-description-SH162',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D11',
    Key: 'awaiting-address-D11-SH162',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-address-D11-description-SH162',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D15',
    Key: 'customer-feedback-D15-SH162',
    Color: 'bg-destructive text-white',
    Description: 'customer-feedback-D15-description-SH162',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D16',
    Key: 'shipping-charges-approval-D16-SH162',
    Color: 'bg-destructive text-white',
    Description: 'shipping-charges-approval-D16-description-SH162',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D18',
    Key: 'oversize-weight-instruction-D18-SH162',
    Color: 'bg-destructive text-white',
    Description: 'oversize-weight-instruction-D18-description-SH162',
  },
  {
    UpdateCode: 'SH162',
    ProblemCode: 'D41',
    Key: 'awaiting-shipper-data-D41-SH162',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-shipper-data-D41-description-SH162',
  },
  {
    UpdateCode: 'SH163',
    ProblemCode: 'D12',
    Key: 'delivery-problem-local-office-D12-SH163',
    Color: 'bg-destructive text-white',
    Description: 'delivery-problem-local-office-D12-description-SH163',
  },
  {
    UpdateCode: 'SH294',
    ProblemCode: 'U12',
    Key: 'awaiting-correct-address-U12-SH294',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-correct-address-U12-description-SH294',
  },
  {
    UpdateCode: 'SH294',
    ProblemCode: 'U14',
    Key: 'customer-unreachable-U14-SH294',
    Color: 'bg-destructive text-white',
    Description: 'customer-unreachable-U14-description-SH294',
  },
  {
    UpdateCode: 'SH294',
    ProblemCode: 'U16',
    Key: 'customer-unreachable-U16-SH294',
    Color: 'bg-destructive text-white',
    Description: 'customer-unreachable-U16-description-SH294',
  },
  {
    UpdateCode: 'SH294',
    ProblemCode: 'U17',
    Key: 'customer-unreachable-U17-SH294',
    Color: 'bg-destructive text-white',
    Description: 'customer-unreachable-U17-description-SH294',
  },

  // Address corrected
  {
    UpdateCode: 'SH295',
    ProblemCode: null,
    Key: 'address-corrected-SH295',
    Color: 'bg-blue-300 text-white',
    Description: 'address-corrected-description-SH295',
  },
  {
    UpdateCode: 'SH296',
    ProblemCode: null,
    Key: 'address-corrected-SH296',
    Color: 'bg-blue-300 text-white',
    Description: 'address-corrected-description-SH296',
  },

  // Pickup statuses
  {
    UpdateCode: 'SH308',
    ProblemCode: null,
    Key: 'pickup-scheduled-SH308',
    Color: 'bg-blue-300 text-white',
    Description: 'pickup-scheduled-description-SH308',
  },
  {
    UpdateCode: 'SH312',
    ProblemCode: null,
    Key: 'pickup-rescheduled-SH312',
    Color: 'bg-blue-300 text-white',
    Description: 'pickup-rescheduled-description-SH312',
  },
  {
    UpdateCode: 'SH313',
    ProblemCode: null,
    Key: 'pickup-cancelled-SH313',
    Color: 'bg-destructive text-white',
    Description: 'pickup-cancelled-description-SH313',
  },
  {
    UpdateCode: 'SH314',
    ProblemCode: null,
    Key: 'pickup-completed-SH314',
    Color: 'bg-success text-white',
    Description: 'pickup-completed-description-SH314',
  },

  // SMS statuses
  {
    UpdateCode: 'SH369',
    ProblemCode: null,
    Key: 'sms-sent-SH369',
    Color: 'bg-blue-300 text-white',
    Description: 'sms-sent-description-SH369',
  },
  {
    UpdateCode: 'SH375',
    ProblemCode: null,
    Key: 'awaiting-correct-address-SH375',
    Color: 'bg-destructive text-white',
    Description: 'awaiting-correct-address-description-SH375',
  },
  {
    UpdateCode: 'SH376',
    ProblemCode: null,
    Key: 'delivery-rescheduled-next-day-SH376',
    Color: 'bg-destructive text-white',
    Description: 'delivery-rescheduled-next-day-description-SH376',
  },
  {
    UpdateCode: 'SH382',
    ProblemCode: null,
    Key: 'shipment-update-SH382',
    Color: 'bg-blue-300 text-white',
    Description: 'shipment-update-description-SH382',
  },
  {
    UpdateCode: 'SH383',
    ProblemCode: null,
    Key: 'payment-completed-SH383',
    Color: 'bg-success text-white',
    Description: 'payment-completed-description-SH383',
  },
  {
    UpdateCode: 'SH407',
    ProblemCode: null,
    Key: 'returned-to-shipper-SH407',
    Color: 'bg-destructive text-white',
    Description: 'returned-to-shipper-description-SH407',
  },

  // Delivery methods
  {
    UpdateCode: 'SH484',
    ProblemCode: null,
    Key: 'delivery-method-aramex-locker-SH484',
    Color: 'bg-blue-300 text-white',
    Description: 'delivery-method-aramex-locker-description-SH484',
  },
  {
    UpdateCode: 'SH491',
    ProblemCode: null,
    Key: 'sms-reminder-SH491',
    Color: 'bg-blue-300 text-white',
    Description: 'sms-reminder-description-SH491',
  },
  {
    UpdateCode: 'SH492',
    ProblemCode: null,
    Key: 'pickup-time-exceeded-SH492',
    Color: 'bg-destructive text-white',
    Description: 'pickup-time-exceeded-description-SH492',
  },
  {
    UpdateCode: 'SH493',
    ProblemCode: null,
    Key: 'delivery-method-changed-SH493',
    Color: 'bg-destructive text-white',
    Description: 'delivery-method-changed-description-SH493',
  },
  {
    UpdateCode: 'SH494',
    ProblemCode: null,
    Key: 'picked-up-from-locker-SH494',
    Color: 'bg-success text-white',
    Description: 'picked-up-from-locker-description-SH494',
  },
  {
    UpdateCode: 'SH498',
    ProblemCode: null,
    Key: 'return-pending-SH498',
    Color: 'bg-destructive text-white',
    Description: 'return-pending-description-SH498',
  },
  {
    UpdateCode: 'SH499',
    ProblemCode: null,
    Key: 'held-at-locker-SH499',
    Color: 'bg-destructive text-white',
    Description: 'held-at-locker-description-SH499',
  },
  {
    UpdateCode: 'SH504',
    ProblemCode: null,
    Key: 'oversize-delivery-method-SH504',
    Color: 'bg-destructive text-white',
    Description: 'oversize-delivery-method-description-SH504',
  },
];

export const cities: string[] = [
  'Agareb',
  'Agoudi Nlkhair',
  'Ain Draham',
  'Ain Jelloula',
  'Ait Mhamed',
  'Akouda',
  'Amdoun',
  'Aousja',
  'Ariana',
  'Azmour',
  'Bab Bhar',
  'Bab Souika',
  'Balta',
  'Bargou',
  'Beja',
  'Beja Nord',
  'Beja Sud',
  'Bekalta',
  'Bembla',
  'Ben Arous',
  'Ben Guerdane',
  'Ben Oun',
  'Beni Hassen',
  'Beni Khalled',
  'Beni Khedache',
  'Beni Khiar',
  "Beni M'tir",
  'Bennane',
  'Bir Ali Ben Khelifa',
  'Bir El Haffey',
  'Bir Lahmar',
  'Bir Mcherga',
  'Bir Salah',
  'Bizerte',
  'Borj El Amri',
  'Bou Arada',
  'Bou Argoub',
  'Bou Ficha',
  'Bou Hajar',
  'Bou Hajla',
  'Bou Merdès',
  'Bou Mhel El Bassatine',
  'Bou Salem',
  'Bradaa',
  'Carthage',
  'Cebbala',
  'Cebbala Ouled Asker',
  'Chaouat',
  'Chebika',
  'Chenini',
  'Cherahil',
  'Cherarda',
  'Chorbane',
  'Cité El Khadra',
  'Cite Ettadhamen',
  'Cite Ezzouhour',
  'Dahmani',
  'Dar Allouche',
  'Dar Châabane El Fehri',
  'Degueche',
  'Denden',
  'Dhehiba',
  'Djebba',
  'Djerba Ajim',
  'Douar Hicher',
  'Douz',
  'El Alâa',
  'El Alia',
  'El Amra',
  'El Aroussa',
  'El Ayoun',
  'El Battan',
  'El Djem',
  'El Fahs',
  'El Faouar',
  'El Guettar',
  'El Hamma',
  'El Haouaria',
  'El Hencha',
  'El Hrairia',
  'El Jem',
  'El Kabaria',
  'El Kram',
  'El Ksar',
  'El Ksour',
  'El Menzah',
  'El Metouia',
  'El Mnihla',
  'El Mourouj',
  'El Omrane',
  'El Omrane Superieur',
  'El Ouerdia',
  'Enfidha',
  'Ennadhour',
  'Essijoumi',
  'Esskhira',
  'Ettahrir',
  'Ezzahra',
  'Feriana',
  'Fernana',
  'Fouchana',
  'Foussana',
  'Gaafour',
  'Gabes',
  'Gafsa',
  'Ghannouche',
  'Ghar El Melh',
  'Ghardimaou',
  'Ghezala',
  'Ghomrassen',
  'Ghraiba',
  'Grombalia',
  'Haffouz',
  'Haidra',
  'Hajeb El Ayoun',
  'Hamma Du Jerid',
  'Hammam Chatt',
  'Hammam El Ghezaz',
  'Hammam Lif',
  'Hammam Sousse',
  'Hammam Zriba',
  'Hammamet',
  'Hassi El Frid',
  'Hbira',
  'Hergla',
  'Hezoua',
  'Houmet Essouk',
  'Jandouba',
  'Jarzouna',
  'Jebel El Ouest',
  'Jebel Jelloud',
  'Jebeniana',
  'Jedaida',
  'Jediliane',
  'Jemmal',
  'Jemna',
  'Jendouba',
  'Jerissa',
  'Jilma',
  'Joumine',
  'Kairouan',
  'Kalaa El Kebira',
  'Kalaa El Khasba',
  'Kalaa Essghira',
  'Kalaat Landlous',
  'Kalaat Sinan',
  'Kalaat Sinane',
  'Kasserine',
  'Kebili',
  'Kelibia',
  'Kerkenah',
  'Kerker',
  'Kesra',
  'Khelidia',
  'Khenis',
  'Kondar',
  'Korba',
  'Korbous',
  'Ksar Helal',
  'Ksar Helal Riadh',
  'Ksibet El Mediouni',
  'Ksour Essaf',
  'La Chebba',
  'La Goulette',
  'La Marsa',
  'La Medina',
  'La Soukra',
  'Lamta',
  'Le Bardo',
  'Le Kef',
  'Le Krib',
  'Le Sers',
  'Lkhir',
  'Maagoula',
  'Maamoura',
  'Mahdia',
  'Mahdia Hiboun',
  'Mahras',
  'Majen Bel Abbes',
  'Maknassy',
  'Makthar',
  'Mannouba',
  'Mareth',
  'Mateur',
  'Matmata',
  'Medenine',
  'Mejel Bel Abbes',
  'Mejez El Bab',
  'Melloulech',
  'Menzel Bourguiba',
  'Menzel Bouzaiene',
  'Menzel Bouzelfa',
  'Menzel Chaker',
  'Menzel Ennour',
  'Menzel Fersi',
  'Menzel Habib',
  'Menzel Hayet',
  'Menzel Horr',
  'Menzel Jemil',
  'Menzel Kamel',
  'Menzel Mhiri',
  'Menzel Salem',
  'Menzel Temime',
  'Merkez Chihya',
  'Mesaken',
  'Messadine',
  'Metlaoui',
  'Metouia',
  'Mezzouna',
  'Mhaya',
  'Midoun',
  'Mnihla',
  'Mohamadia',
  'Moknine',
  'Monastir',
  'Mornag',
  'Mornaguia',
  'Moulares',
  'Msaken',
  'Mtioua',
  'Nabeul',
  'Nasrallah',
  'Nebeur',
  'Nefta',
  'Nefza',
  'Nouvelle Matmata',
  'Nouvelle Medina',
  'Nzalat Bni Amar',
  'Oudhref',
  'Oued Ellil',
  'Oued Mliz',
  'Ouerdanine',
  'Oueslatia',
  'Oulad Mrah',
  'Ouled Haffouz',
  'Rades',
  'Rafraf',
  'Raoued',
  'Ras Jebel',
  'Redeyef',
  'Regueb',
  'Rejiche',
  'Remada',
  'Rohia',
  'Sahline',
  'Sakiet Eddaier',
  'Sakiet Ezzit',
  'Sakiet Sidi Youssef',
  'Saouef',
  'Sayada',
  'Sayada Lamta Bou Hajar',
  'Sbeitla',
  'Sbiba',
  'Sbikha',
  'Sejnane',
  'Sfax',
  'Sidi Aich',
  'Sidi Alouene',
  'Sidi Bannour',
  'Sidi Bou Ali',
  'Sidi Bousaid',
  'Sidi Bouzid',
  'Sidi El Bechir',
  'Sidi El Heni',
  'Sidi Hassine',
  'Sidi Makhlouf',
  'Sidi Mhamed Chelh',
  'Sidi Salah',
  'Sidi Thabet',
  'Siliana',
  'Skoura Mdaz',
  'Smar',
  'Sned',
  'Soliman',
  'Souassi',
  'Souk El Ahad',
  'Souk Jedid',
  'Souk Lqolla',
  'Sousse',
  'Tabarka',
  'Tajerouine',
  'Takelsa',
  'Tameghza',
  'Tamezrat',
  'Tataouine',
  'Tazarka',
  'Teboulba',
  'Tebourba',
  'Teboursouk',
  'Testour',
  'Thala',
  'Thelepte',
  'Thibar',
  'Tinja',
  'Tlelsa',
  'Touiref',
  'Touza',
  'Tozeur',
  'Tunis Republique',
  'Tyna',
  'Utique',
  'Zaghouan',
  'Zahret Mediene',
  'Zaouiet Jedidi',
  'Zarat',
  'Zarzis',
  'Zeramdine',
  'Zriba',
];
