import { NavItem, OrderStatusType } from '@/types';
import {
  IconBoxSeam,
  IconBrandYoutube,
  IconBuildingStore,
  IconBuildingWarehouse,
  IconCurrentLocation,
  IconLayoutDashboard,
  IconNotebook,
  IconPackage,
  IconPackageExport,
  IconPackageOff,
  IconReceipt2,
  IconSettings,
  IconTruckDelivery,
  IconTruckLoading,
  IconTruckOff,
  IconUser,
  IconUserPlus,
  IconUserQuestion,
  IconUsers,
} from '@tabler/icons-react';

export enum packOptions {
  DAMREJ = 'DAMREJ',
  AJEJA = 'AJEJA',
  MACHROU3 = 'MACHROU3',
}
export enum roleOptions {
  ADMIN = 'ADMIN',
  SELLER = 'SELLER',
  SUPPLIER = 'SUPPLIER',
}

export const adminNavItems: NavItem[] = [
  {
    title: 'dashboard',
    href: '/dashboard/admin',
    icon: <IconLayoutDashboard />,
  },
  {
    title: 'marketplace',
    href: '/dashboard/marketplace',
    icon: <IconBuildingStore />,
  },
  {
    title: 'leads',
    href: '/dashboard/admin/leads',
    icon: <IconUserQuestion />,
  },
  {
    title: 'course',
    href: '/dashboard/admin/course',
    icon: <IconBrandYoutube />,
  },
  {
    title: 'sellers',
    href: '/dashboard/admin/sellers',
    icon: <IconUsers />,
  },
  {
    title: 'suppliers',
    href: '/dashboard/admin/suppliers',
    icon: <IconBuildingWarehouse />,
  },
  {
    title: 'products',
    href: '/dashboard/admin/products',
    icon: <IconBoxSeam />,
  },
  {
    title: 'orders',
    href: '/dashboard/admin/orders',
    icon: <IconTruckDelivery />,
  },
  {
    title: 'transactions',
    href: '/dashboard/admin/transactions',
    icon: <IconReceipt2 />,
  },
  {
    title: 'settings',
    href: '/dashboard/admin/settings',
    icon: <IconSettings />,
  },
];

export const sellerNavItems: NavItem[] = [
  {
    title: 'dashboard',
    href: '/dashboard/seller',
    icon: <IconLayoutDashboard />,
  },
  {
    title: 'marketplace',
    href: '/dashboard/marketplace',
    icon: <IconBuildingStore />,
  },
  {
    title: 'course',
    href: '/dashboard/seller/course',
    icon: <IconBrandYoutube />,
  },
  {
    title: 'my-products',
    href: '/dashboard/seller/my-products',
    icon: <IconBoxSeam />,
  },
  {
    title: 'orders',
    href: '/dashboard/seller/orders',
    icon: <IconTruckDelivery />,
  },
  {
    title: 'transactions',
    href: '/dashboard/seller/transactions',
    icon: <IconReceipt2 />,
  },
  {
    title: 'settings',
    href: '/dashboard/seller/settings',
    icon: <IconSettings />,
  },
];

export const supplierNavItems: NavItem[] = [
  {
    title: 'dashboard',
    href: '/dashboard/supplier',
    icon: <IconLayoutDashboard />,
  },
  {
    title: 'marketplace',
    href: '/dashboard/marketplace',
    icon: <IconBuildingStore />,
  },
  {
    title: 'products',
    href: '/dashboard/supplier/products',
    icon: <IconBoxSeam />,
  },
  {
    title: 'orders',
    href: '/dashboard/supplier/orders',
    icon: <IconTruckDelivery />,
  },
  {
    title: 'transactions',
    href: '/dashboard/supplier/transactions',
    icon: <IconReceipt2 />,
  },
  {
    title: 'settings',
    href: '/dashboard/supplier/settings',
    icon: <IconSettings />,
  },
];

export const MEDIA_HOSTNAME = 'https://utfs.io/f/';

export const notificationIcons = {
  ADMIN_NEW_PRODUCT: IconPackage,
  ADMIN_NEW_SELLER: IconUserPlus,
  ADMIN_NEW_LEAD: IconUserQuestion,
  SUPPLIER_PRODUCT_PUBLISHED: IconPackageExport,
  SUPPLIER_PRODUCT_UNPUBLISHED: IconPackageOff,
  SUPPLIER_NEW_ORDER: IconTruckDelivery,
  ADMIN_NEW_ORDER: IconTruckDelivery,
  SELLER_STOCK_CHANGED: IconTruckLoading,
  ORDER_STATUS_CHANGED: IconCurrentLocation,
  ORDER_CANCELLED: IconTruckOff,
};

export const notificationMessages = {
  ADMIN_NEW_PRODUCT: 'admin-new-product',
  ADMIN_NEW_SELLER: 'admin-new-seller',
  ADMIN_NEW_LEAD: 'admin-new-lead',
  SUPPLIER_PRODUCT_PUBLISHED: 'supplier-product-published',
  SUPPLIER_PRODUCT_UNPUBLISHED: 'supplier-product-unpublished',
  SUPPLIER_NEW_ORDER: 'supplier-new-order',
  ADMIN_NEW_ORDER: 'admin-new-order',
  SELLER_STOCK_CHANGED: 'seller-stock-changed',
  ORDER_STATUS_CHANGED: 'order-status-changed',
  ORDER_CANCELLED: 'order-cancelled',
};

export const localeOptions = {
  EN: 'en',
  FR: 'fr',
};

export const DEFAULT_PASSWORD = 'ECOMNESS2024';

export enum productCategoryOptions {
  FURNITURE = 'FURNITURE',
  ACCESSORIES = 'ACCESSORIES',
  KITCHEN = 'KITCHEN',
  DECORATION = 'DECORATION',
  CAR_ACCESSORIES = 'CAR_ACCESSORIES',
  HOME_APPLIANCES = 'HOME_APPLIANCES',
  ELECTRONICS = 'ELECTRONICS',
  CLOTHING = 'CLOTHING',
  BEAUTY = 'BEAUTY',
  SPORTS = 'SPORTS',
  TOYS = 'TOYS',
  JEWELRY = 'JEWELRY',
  GARDEN = 'GARDEN',
}

export const productCategoryData = [
  {
    name: productCategoryOptions.FURNITURE,
    imageUrl: '/img/furniture.png',
  },
  {
    name: productCategoryOptions.ACCESSORIES,
    imageUrl: '/img/accessories.png',
  },
  {
    name: productCategoryOptions.KITCHEN,
    imageUrl: '/img/kitchen.png',
  },
  {
    name: productCategoryOptions.DECORATION,
    imageUrl: '/img/decoration.png',
  },
  {
    name: productCategoryOptions.TOYS,
    imageUrl: '/img/baby-kids.webp',
  },
  {
    name: productCategoryOptions.HOME_APPLIANCES,
    imageUrl: '/img/appliances.webp',
  },

  {
    name: productCategoryOptions.ELECTRONICS,
    imageUrl: '/img/technology.webp',
  },
  {
    name: productCategoryOptions.CLOTHING,
    imageUrl: '/img/fashion.png',
  },
  {
    name: productCategoryOptions.BEAUTY,
    imageUrl: '/img/beauty.webp',
  },
  {
    name: productCategoryOptions.GARDEN,
    imageUrl: '/img/garden.png',
  },
  {
    name: productCategoryOptions.SPORTS,
    imageUrl: '/img/sport.webp',
  },
  {
    name: productCategoryOptions.CAR_ACCESSORIES,
    imageUrl: '/img/auto-parts.webp',
  },
  {
    name: productCategoryOptions.JEWELRY,
    imageUrl: '/img/jewelry.png',
  },
];

export enum sizeOptions {
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
  XXL = 'XXL',
  XXXL = 'XXXL',
}

export enum colorOptions {
  RED = 'RED',
  BLUE = 'BLUE',
  GREEN = 'GREEN',
  YELLOW = 'YELLOW',
  BLACK = 'BLACK',
  WHITE = 'WHITE',
  ORANGE = 'ORANGE',
  PURPLE = 'PURPLE',
  PINK = 'PINK',
  LIGHT_BLUE = 'LIGHT_BLUE',
  NAVY_BLUE = 'NAVY_BLUE',
  TURQUOISE = 'TURQUOISE',
  BEIGE = 'BEIGE',
  BROWN = 'BROWN',
  GRAY = 'GRAY',
}

export const colorHexMap: { [key in colorOptions]: string } = {
  [colorOptions.RED]: '#FF0000',
  [colorOptions.BLUE]: '#0000FF',
  [colorOptions.GREEN]: '#00FF00',
  [colorOptions.YELLOW]: '#FFFF00',
  [colorOptions.BLACK]: '#000000',
  [colorOptions.WHITE]: '#FFFFFF',
  [colorOptions.ORANGE]: '#FFA500',
  [colorOptions.PURPLE]: '#800080',
  [colorOptions.PINK]: '#FFC0CB',
  [colorOptions.LIGHT_BLUE]: '#ADD8E6',
  [colorOptions.NAVY_BLUE]: '#000080',
  [colorOptions.TURQUOISE]: '#40E0D0',
  [colorOptions.BEIGE]: '#F5F5DC',
  [colorOptions.BROWN]: '#A52A2A',
  [colorOptions.GRAY]: '#808080',
};

export const orderStatuses: OrderStatusType[] = [
  { UpdateCode: 'EC01', Key: 'packaged-ready', Color: 'bg-success text-white' },
  { UpdateCode: 'EC02', Key: 'seller-cancelled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH001', Key: 'at-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH002', Key: 'at-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH003', Key: 'out-for-delivery', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH004', Key: 'partial-out-for-delivery', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH005', Key: 'delivered', Color: 'bg-success text-white' },
  { UpdateCode: 'SH006', Key: 'collected', Color: 'bg-success text-white' },
  { UpdateCode: 'SH007', Key: 'postal-delivery', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH008', Key: 'on-hold', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH011', Key: 'picked-up', Color: 'bg-success text-white' },
  { UpdateCode: 'SH012', Key: 'picked-up', Color: 'bg-success text-white' },
  { UpdateCode: 'SH014', Key: 'record-created', Color: 'bg-gray-300 text-white' },
  { UpdateCode: 'SH017', Key: 'n-a', Color: 'bg-gray-300 text-white' },
  { UpdateCode: 'SH024', Key: 'n-a', Color: 'bg-gray-300 text-white' },
  { UpdateCode: 'SH030', Key: 'still-on-hold', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH033', Key: 'attempted-delivery', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH034', Key: 'docs-delivered', Color: 'bg-success text-white' },
  { UpdateCode: 'SH035', Key: 'awaiting-clearance', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH041', Key: 'cleared-customs', Color: 'bg-success text-white' },
  { UpdateCode: 'SH043', Key: 'delay-rescheduled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH044', Key: 'delay-rescheduled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH047', Key: 'origin-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH069', Key: 'to-be-returned', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH070', Key: 'redirected-address', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH073', Key: 'forwarded-remote-location', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH076', Key: 'situation-update', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH077', Key: 'forwarded-aramex-office', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH110', Key: 'forwarded-delivery-office', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH154', Key: 'partial-delivery', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH156', Key: 'customs-clearance', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH157', Key: 'unable-to-forward', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH158', Key: 'customs-clearance', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH160', Key: 'at-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH162', Key: 'on-hold', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH163', Key: 'delivery-problem', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH164', Key: 'held-for-pickup', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH203', Key: 'record-created', Color: 'bg-gray-300 text-white' },
  { UpdateCode: 'SH215', Key: 'at-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH234', Key: 'delivered-letter-box', Color: 'bg-success text-white' },
  { UpdateCode: 'SH247', Key: 'docs-returned', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH249', Key: 'sms-consignee', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH250', Key: 'shipper-contacted', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH251', Key: 'third-party-contacted', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH252', Key: 'forwarded-remote-location', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH261', Key: 'email-consignee', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH271', Key: 'sms-consignee', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH272', Key: 'forwarded-destination', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH273', Key: 'delivery-scheduled', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH275', Key: 'on-hold-facility', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH280', Key: 'confiscated-customs', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH281', Key: 'docs-out-for-delivery', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH308', Key: 'pickup-scheduled', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH312', Key: 'pickup-rescheduled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH313', Key: 'pickup-cancelled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH314', Key: 'pickup-completed', Color: 'bg-success text-white' },
  { UpdateCode: 'SH369', Key: 'sms-consignee', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH376', Key: 'delay-rescheduled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH382', Key: 'shipment-update', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH383', Key: 'payment-completed', Color: 'bg-success text-white' },
  { UpdateCode: 'SH406', Key: 'origin-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH407', Key: 'returned-to-shipper', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH410', Key: 'contact-attempts-completed', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH484', Key: 'aramex-locker', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH491', Key: 'sms-reminder', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH492', Key: 'locker-time-exceeded', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH493', Key: 'locker-delivery-method-changed', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH494', Key: 'picked-up-from-locker', Color: 'bg-success text-white' },
  { UpdateCode: 'SH495', Key: 'at-facility', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH496', Key: 'picked-up', Color: 'bg-success text-white' },
  { UpdateCode: 'SH498', Key: 'contact-attempts-completed', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH499', Key: 'held-at-locker', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH504', Key: 'delivery-method-oversize', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH505', Key: 'payment-cancelled', Color: 'bg-destructive text-white' },
  { UpdateCode: 'SH513', Key: 'auto-scheduled-delivery', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH515', Key: 'courier-called-customer', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH516', Key: 'customer-called-courier', Color: 'bg-blue-300 text-white' },
  { UpdateCode: 'SH521', Key: 'local-office-prepared-for-collection', Color: 'bg-blue-300 text-white' },
];

export const cities: string[] = [
  'Agareb',
  'Ain Draham',
  'Bab Souika',
  'Bargou',
  'Beja',
  'Bembla',
  'Ben Arous',
  'Ben Oun',
  "Beni M'Tir",
  'Bir Lahmar',
  'Bir Mcherga',
  'Bir Salah',
  'Matmata',
  'Bou Arada',
  'Bou Salem',
  'Chenini',
  'Dahmani',
  'Dar Allouche',
  'Beni Khedache',
  'El Hamma',
  'Degueche',
  'Menzel Habib',
  'Ben Guerdane',
  'Dhehiba',
  'Djebba',
  'Sidi Makhlouf',
  'Djerba Ajim',
  'Korba',
  'Menzel Horr',
  'Douz',
  'Beni Khalled',
  'El Alia',
  'Azmour',
  'Dar Châabane El Fehri',
  'El Haouaria',
  'El Mida',
  'Takelsa',
  'Hammamet',
  'El Amra',
  'El Aroussa',
  'El Ayoun',
  'Menzel Bouzelfa',
  'El Battan',
  'Bou Argoub',
  'El Hencha',
  'Menzel Temime',
  'Menzel Salem',
  'Beni Khiar',
  'Kelibia',
  'Nabeul',
  'El Kram',
  'El Metouia',
  'Sakiet Eddaier',
  'El Mnihla',
  'Enfidha',
  'Esskhira',
  'Feriana',
  'Fernana',
  'Sidi Salah',
  'Foussana',
  'Gabes',
  'Jebeniana',
  'Menzel Chaker',
  'Sfax',
  'Ghannouche',
  'Mahres',
  'Kerkennah',
  'Menzel Fersi',
  'Sousse',
  'Mesaken',
  'Oueslatia',
  'Ain Jelloula',
  'Menzel Hayet',
  'Touza',
  'Bradaa',
  'Kerker',
  'Sidi Alouene',
  'Ghardimaou',
  'Ghomrassen',
  'Sidi Bannour',
  'Chebika',
  'Rejiche',
  'Khenis',
  'Bou Hajla',
  'El Alâa',
  'Msaken',
  'Sayada Lamta Bou Hajar',
  'Bou Merdès',
  'El Djem',
  'Ghraiba',
  'La Chebba',
  'Jemmal',
  'Moknine',
  'Bou Ficha',
  'Bennane',
  'Ksibet El Mediouni',
  'Lamta',
  'Hergla',
  'Grombalia',
  'Akouda',
  'Menzel Ennour',
  'Sidi Bou Ali',
  'Chorbane',
  'Hamma Du Jerid',
  'Kondar',
  'Hammam El Ghezaz',
  'Hammam Lif',
  'Mahdia',
  'Bekalta',
  'Hbira',
  'Houmet Essouk',
  'Jandouba',
  'Jarzouna',
  'Jebel El Ouest',
  'Jedaida',
  'Cherahil',
  'Sahline',
  'Hajeb El Ayoun',
  'Sbikha',
  'Haffouz',
  'Beni Hassen',
  'Kairouan',
  'Bou Hajar',
  'Jediliane',
  'Ksar Helal Riadh',
  'Hammam Sousse',
  'Kalaa El Kebira',
  'Melloulech',
  'Bir Ali Ben Khelifa',
  'Teboulba',
  'Jendouba',
  'Zeramdine',
  'Cherarda',
  'Messadine',
  'Ksour Essaf',
  'Sayada',
  'El Jem',
  'Metline',
  'Cite Ezzouhour',
  'Sidi Bousaid',
  'Khelidia',
  'Ariana',
  'Mornag',
  'Menzel Bourguiba',
  'Sidi Hassine',
  'Naassen',
  'Jilma',
  'Aousja',
  'Sidi Daoud',
  'Rafraf',
  'Ras Jebel',
  'Zaghouan',
  'Kalaa El Khasba',
  'Kalaa Essghira',
  'Kalaat Landlous',
  'Megrine',
  'Kalaat Sinan',
  'Kalaat Sinane',
  'Raoued',
  'Oued Ellil',
  'Borj El Amri',
  'Kasserine',
  'Tunis',
  'Sejnane',
  'Ezzahra',
  'Korbous',
  'Bizerte',
  'Hammam Chatt',
  'Rades',
  'Ghezala',
  'Ksar Helal',
  'Joumine',
  'La Goulette',
  'La Soukra',
  'Mnihla',
  'Bou Mhel El Bassatine',
  'El Mourouj',
  'Nouvelle Medina',
  'La Marsa',
  'Maagoula',
  'Mannouba',
  'Bab Bhar',
  'Maamoura',
  'Cité El Khadra',
  'El Hrairia',
  'El Kabaria',
  'Mahdia Hiboun',
  'El Menzah',
  'El Omrane',
  'El Omrane Superieur',
  'El Ouerdia',
  'Essijoumi',
  'Ettahrir',
  'Jebel Jelloud',
  'Mareth',
  'Mateur',
  'La Medina',
  'Le Bardo',
  'Medenine',
  'Mejez El Bab',
  'El Fahs',
  'Hammam Zriba',
  'Menzel Jemil',
  'Menzel Kamel',
  'Ennadhour',
  'Zriba',
  'Douar Hicher',
  'Carthage',
  'Chaouat',
  'Sidi Thabet',
  'Fouchana',
  'Cite Ettadhamen',
  'Tebourba',
  'Ghar El Melh',
  'Mornaguia',
  'Denden',
  'Menzel Mhiri',
  'Merkez Chihya',
  'Thelepte',
  'Metouia',
  'Majen Bel Abbes',
  'Metlaoui',
  'Sidi Bouzid',
  'Jemna',
  'Cebbala',
  'Kebili',
  'Mezzouna',
  'Midoun',
  'Haidra',
  'Bir El Haffey',
  'Menzel Bouzaiene',
  'Lkhir',
  'El Guettar',
  'El Ksar',
  'Mohamadia',
  'Monastir',
  'Moulares',
  'Hassi El Frid',
  'Mejel Bel Abbes',
  'El Faouar',
  'Hezoua',
  'Tameghza',
  'Nasrallah',
  'Maknassy',
  'Gafsa',
  'Sbeitla',
  'Nouvelle Matmata',
  'Oudhref',
  'Nefta',
  'Regueb',
  'Tozeur',
  'Oued Mliz',
  'Redeyef',
  'Souk El Ahad',
  'Ouerdanine',
  'Ouled Chamakh',
  'Ouled Haffouz',
  'Remada',
  'Rohia',
  'Sbiba',
  'Cebbala Ouled Asker',
  'Souk Jedid',
  'Amdoun',
  'Beja Nord',
  'Beja Sud',
  'Sakiet Ezzit',
  'Balta',
  'El Ksour',
  'Sakiet Sidi Youssef',
  'Le Kef',
  'Saouef',
  'Le Sers',
  'Sidi Aich',
  'Sidi Bou Rouis',
  'Le Krib',
  'Teboursouk',
  'Sidi El Bechir',
  'Sidi El Heni',
  'Siliana',
  'Gaafour',
  'Smar',
  'Sned',
  'Soliman',
  'Souassi',
  'Tabarka',
  'Nebeur',
  'Tajerouine',
  'Nefza',
  'Tamezrat',
  'Tataouine',
  'Tazarka',
  'Testour',
  'Thala',
  'Thibar',
  'Tinja',
  'Tlelsa',
  'Touiref',
  'Tyna',
  'Jerissa',
  'Goubellat',
  'Zahret Mediene',
  'Kesra',
  'Utique',
  'Zaouiet Jedidi',
  'Zarat',
  'Zarzis',
  'Makthar',
];
